SELECT format('CREATE DATABASE %I', :'AUTH_DB_NAME')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'AUTH_DB_NAME') \gexec

SELECT format('CREATE DATABASE %I', :'USER_DB_NAME')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'USER_DB_NAME') \gexec

SELECT format('CREATE DATABASE %I', :'PORTFOLIO_DB_NAME')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'PORTFOLIO_DB_NAME') \gexec

SELECT format('CREATE DATABASE %I', :'MARKET_DATA_DB_NAME')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'MARKET_DATA_DB_NAME') \gexec

SELECT format('CREATE DATABASE %I', :'PREDICTION_DB_NAME')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'PREDICTION_DB_NAME') \gexec

SELECT format('CREATE DATABASE %I', :'ANALYTICS_DB_NAME')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'ANALYTICS_DB_NAME') \gexec
