server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

jwt:
  issuer: ${JWT_ISSUER:investment-helper-auth-service}
  public-key-path: ${JWT_PUBLIC_KEY_PATH:classpath:keys/public.pem}

app:
  bootstrap-admin:
    enabled: true
    auth-user-id: 1
    first-name: System
    last-name: Administrator
    date-of-birth: 2000-01-01