spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/investment_helper_market_data
    username: postgres
    password: your_local_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true